- id: '1590521213994'
  alias: Washing machine water sensor
  description: ''
  trigger:
  - entity_id: binary_sensor.water_sensor_1
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: Washing machine water sensor triggered!
    service: notify.primary
- id: '1597951896909'
  alias: Turn off after time demo
  description: ''
  trigger:
  - device_id: abd6032571a042d8b16ef846417a176c
    domain: switch
    entity_id: switch.desk_lamp_relay
    for:
      hours: 2
      minutes: 0
      seconds: 0
    platform: device
    type: turned_on
  condition: []
  action:
  - device_id: abd6032571a042d8b16ef846417a176c
    domain: switch
    entity_id: switch.desk_lamp_relay
    type: turn_off
  mode: single
- id: '1662082206171'
  alias: Bedroom lamp button single turn on ve
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.button_0057_action
    to: single
  condition:
  - condition: state
    state: 'off'
    entity_id: light.bulb_0056
  action:
  - service: light.turn_on
    data:
      color_temp: 270
      transition: 0
      brightness_pct: 0
    target:
      entity_id: light.bulb_0056
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
    enabled: false
  - service: light.turn_on
    data:
      transition: 0
      brightness_pct: 100
      color_temp: 270
    target:
      entity_id: light.bulb_0056
  mode: single
- id: '1662082583068'
  alias: Bedroom lamp button single turn off ve
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.button_0057_action
    to: single
  condition:
  - condition: state
    entity_id: light.bulb_0056
    state: 'on'
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.bulb_0056
  mode: single
- id: '1662082644203'
  alias: Bedroom lamp button long press ve
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.button_0057_action
    to: long
  condition: []
  action:
  - service: light.turn_on
    data:
      rgb_color:
      - 255
      - 0
      - 0
      brightness_pct: 15
    target:
      entity_id: light.bulb_0056
  mode: single
- id: '1662093369982'
  alias: test test
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.button_0058_action
    to: single
  condition: []
  action:
  - type: toggle
    device_id: 5180f266ed254be48fdf9218ccd8ab13
    entity_id: light.basement_table_ceiling_fan_lights
    domain: light
  mode: single
- id: '1662154713030'
  alias: Luke Diamond Light turn on
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.button_0058_action
    to: single
  condition:
  - condition: state
    entity_id: light.bulb_0055
    state: 'off'
  action:
  - service: light.turn_on
    data:
      transition: 3
      brightness_pct: 100
      color_temp: 315
      rgb_color:
      - 255
      - 255
      - 255
    target:
      entity_id: light.bulb_0055
  mode: single
- id: '1662154805178'
  alias: Luke Diamond Light turn off
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.button_0058_action
    to: single
  condition:
  - condition: state
    entity_id: light.bulb_0055
    state: 'on'
  action:
  - service: light.turn_off
    data:
      transition: 1
    target:
      entity_id: light.bulb_0055
  mode: single
- id: '1662156895666'
  alias: Luke Diamond Light party mode
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.button_0058_action
    to: double
  condition: []
  action:
  - service: light.turn_on
    data:
      transition: 5
      brightness_pct: 100
      rgb_color:
      - 255
      - 0
      - 0
    target:
      entity_id: light.bulb_0055
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: light.turn_on
    data:
      transition: 5
      brightness_pct: 100
      rgb_color:
      - 255
      - 136
      - 0
    target:
      entity_id: light.bulb_0055
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: light.turn_on
    data:
      transition: 5
      brightness_pct: 100
      rgb_color:
      - 255
      - 255
      - 0
    target:
      entity_id: light.bulb_0055
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: light.turn_on
    data:
      transition: 5
      brightness_pct: 100
      rgb_color:
      - 0
      - 255
      - 0
    target:
      entity_id: light.bulb_0055
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: light.turn_on
    data:
      transition: 5
      brightness_pct: 100
      rgb_color:
      - 0
      - 0
      - 255
    target:
      entity_id: light.bulb_0055
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: light.turn_on
    data:
      transition: 5
      brightness_pct: 100
      rgb_color:
      - 170
      - 0
      - 255
    target:
      entity_id: light.bulb_0055
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: light.turn_on
    data:
      transition: 5
      brightness_pct: 100
      rgb_color:
      - 255
      - 0
      - 0
    target:
      entity_id: light.bulb_0055
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  mode: parallel
  max: 100
- id: '1662176346051'
  alias: Luke Diamond Light Sleep mode
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.button_0058_action
    to: long
  condition: []
  action:
  - service: light.turn_on
    data:
      transition: 1
      brightness_pct: 1
      color_temp: 375
    target:
      entity_id: light.bulb_0055
  mode: single
- id: '1710996246602'
  alias: Cube Aquarium Refugium Light On
  description: ''
  trigger:
  - platform: time
    at: '20:00:00'
  condition: []
  action:
  - service: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.cube_aquarium_power_strip_outlet_1
  mode: single
- id: '1710996314281'
  alias: Cube Aquarium Refugium Light Off
  description: ''
  trigger:
  - platform: time
    at: 08:00:00
  condition: []
  action:
  - service: switch.turn_off
    target:
      entity_id:
      - switch.cube_aquarium_power_strip_outlet_1
    data: {}
  mode: single
- id: '1711470600001'
  alias: Auto Water Change Counter Aquarium
  description: "Auto water change for the counter top aquarium system.\n\n74 liter
    total volume\n15 percent = 13.3 minutes\n10 percent = 8.8 minutes\n  5 percent
    = 4.4 minutes\n  2 min = 2.3 %\n  4 min = 4.5 %"
  trigger:
  - platform: time
    at: '10:30:00'
  - platform: time
    at: '10:45:00'
    enabled: false
  condition:
  - condition: state
    entity_id: binary_sensor.drain_sump_reservoir_full_sensor
    state: 'off'
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.aquarium_02_pump
    data: {}
  - delay: 00:02:00
  - service: switch.turn_off
    target:
      entity_id: switch.aquarium_02_pump
    data: {}
  mode: single
- id: '1714074206373'
  alias: ATO/WC Fill Tank Empty Alarm
  description: ''
  trigger:
  - entity_id: binary_sensor.aquarium_ato_wc_fill_reservoir_empty_sensor
    platform: state
    from: 'off'
    to: 'on'
    for: 00:15:00
  condition: []
  action:
  - service: notify.aquarium_ato_wc_group
    data:
      message: Aquarium ATO/WC fill tank empty!
  mode: single
- id: '1714074356077'
  alias: ATO/WC Drain Tank Full Alarm
  description: ''
  trigger:
  - entity_id: binary_sensor.aquarium_ato_wc_drain_reservoir_full_sensor
    platform: state
    from: 'off'
    to: 'on'
    for: 00:15:00
  condition: []
  action:
  - service: notify.aquarium_ato_wc_group
    data:
      message: Aquarium ATO/WC drain tank full!
  mode: single
- id: '1714074884992'
  alias: CO2 Off
  description: ''
  trigger:
  - platform: time
    at:
    - '16:00:00'
    - '17:00:00'
    - '18:00:00'
    - '19:00:00'
    - '20:00:00'
    - '21:00:00'
    - '22:00:00'
    - '23:00:00'
  condition: []
  action:
  - service: switch.turn_off
    data:
      entity_id: switch.co2_valve
  mode: single
- id: '1714074895839'
  alias: CO2 On
  description: ''
  trigger:
  - platform: time
    at:
    - 09:00:00
  condition: []
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.co2_valve
  mode: single
- id: '1714075329817'
  alias: Coffee Maker Start
  description: ''
  trigger:
  - platform: time
    at: input_datetime.coffee_maker_start
  condition:
  - condition: state
    entity_id: input_boolean.enable_coffee_maker
    state: 'on'
  action:
  - service: switch.turn_on
    entity_id: switch.coffee_maker
  - service: input_boolean.turn_off
    entity_id: input_boolean.enable_coffee_maker
  - delay: 0:15
  - service: switch.turn_off
    entity_id: switch.coffee_maker
  mode: single
