wifi:
  ssid: !secret iot_wifi
  password: !secret iot_wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: $name Fallback Hotspot
    password: !secret fallback_wifi_password

captive_portal:

# Enable Home Assistant API
api:
  reboot_timeout: 2h
  #password: !secret esphomeapipwd

ota:
  #password: !secret esphomeotapwd

web_server:
  port: 80
