substitutions:
  name: controller038
  description: Aquarium Auto Top Off

# Enable logging
logger:

<<: !include include/common.yaml

esphome:
  name: $name
  platform: ESP8266
  board: d1_mini

servo:

  - id: pump_1
    output: pwm_d7
    min_level: 0
    idle_level: 0
    max_level: 1

  - id: pump_2
    output: pwm_d1
    min_level: 0
    idle_level: 0
    max_level: 1


binary_sensor:

  - platform: gpio
    id: pump_1_water_sensor
    pin:
      number: D6
      mode: INPUT_PULLUP
    name: $description Pump 1 Water Sensor
    filters:
      - invert:

  - platform: gpio
    id: pump_2_water_sensor
    pin:
      number: D2
      mode: INPUT_PULLUP
    name: $description Pump 2 Water Sensor
    filters:
      - invert:

  - platform: gpio
    id: tank_water_sensor
    pin:
      number: D5
      mode: INPUT_PULLUP
    name: $description Tank Water Sensor
    filters:
      - invert:
      - delayed_on_off: 1s
    on_press:
      then:
        - servo.write:
            id: pump_2
            level: 95%
    on_release:
      then:
        - servo.detach: pump_2

output:

  - platform: esp8266_pwm
    id: pwm_d7
    pin: D7
    frequency: 20000 Hz

  - platform: esp8266_pwm
    id: pwm_d1
    pin: D1
    frequency: 20000 Hz

api:
  services:

    - service: control_pump_1
      variables:
        level: float
      then:
        - logger.log:
            format: "Pump 1 called with value %.1f"
            args: [ 'level' ]
        - servo.write:
            id: pump_1
            level: !lambda 'return level / 100.0;'

    - service: control_pump_2
      variables:
        level: float
      then:
        - logger.log:
            format: "Pump 2 called with value %.1f"
            args: [ 'level' ]
        - servo.write:
            id: pump_2
            level: !lambda 'return level / 100.0;'
