substitutions:
  name: controller070
  description: Cube Aquarium ATO WC Controller
  static_ip: ""

ota:
  - platform: esphome

# Enable logging
logger:

packages:
  base: !include include/base.yaml
  wifi: !include include/wifi_not.yaml

esphome:
  name: $name
  comment: $description
  platform: ESP32
  board: esp32doit-devkit-v1

  on_boot:
    priority: -100
    then:
      - script.execute: set_fill_valve_on_off
      - if:
          condition:
            and:
              - switch.is_on: ato_enabled
          then:
            - logger.log: "Start up ato enabled"
          else:
            - logger.log: "Start up ato disabled"


number:

  - platform: template
    name: Error delay (m)
    id: error_delay
    icon: mdi:numeric
    restore_value: true
    initial_value: 10
    optimistic: true
    min_value: 1
    step: 1
    max_value: 120

script:

  - id: fill_duration_guard
    then:
      - delay: !lambda "return id(error_delay).state * 1000 * 60;"
      - switch.turn_on: error_fill_duration_exceeded
      - switch.turn_off: relay_valve

  - id: set_fill_valve_on_off
    then:
      - logger.log: "set_fill_valve_on_off"
      - delay: 50ms
      - if:
          condition:
            and:
              - switch.is_off: error_fill_duration_exceeded
              - switch.is_on: ato_enabled
              - binary_sensor.is_off: sump_full
          then:
            - logger.log: "turn on relay_valve"
            - switch.turn_on: relay_valve
            - script.execute: fill_duration_guard
      - if:
          condition:
            or:
              - binary_sensor.is_on: sump_full
          then:
            - logger.log: "turn off relay_valve"
            - switch.turn_off: relay_valve
            - script.stop: fill_duration_guard

binary_sensor:

  - platform: gpio
    name: $description Button Pump
    pin:
      number: GPIO26
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on_off: 50ms
    on_press:
      - switch.toggle: relay_pump_pub

  - platform: gpio
    name: $description Button Valve
    pin:
      number: GPIO27
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on_off: 50ms
    on_press:
          then:
            - switch.toggle: relay_valve

  - platform: gpio
    name: $description Sump Full
    id: sump_full
    pin:
      number: GPIO16
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on_off: 25ms
    on_state:
      then:
        - logger.log: "Sump Full On"
        - script.execute: set_fill_valve_on_off

  - platform: gpio

    name: $description Sump Low
    id: sump_low
    pin:
      number: GPIO17
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on_off: 50ms
    on_press:
      then:
        - switch.turn_off: relay_pump

  - platform: gpio
    name: $description Moisture Sensor
    pin:
      number: GPIO21
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on_off: 1s

switch:

  - platform: gpio
    id: relay_pump
    pin: GPIO2
    restore_mode: ALWAYS_OFF

  - platform: gpio
    id: relay_valve
    pin: GPIO4
    restore_mode: ALWAYS_OFF

  - platform: template
    name: $description Valve
    id: relay_valve_pub
    lambda: |-
      return id(relay_valve).state;
    turn_on_action:
      - logger.log: "Valve turn on"
      - switch.turn_on: relay_valve
      - script.execute: fill_duration_guard
    turn_off_action:
      - logger.log: "valve turn off"
      - switch.turn_off: relay_valve
      - script.stop: fill_duration_guard

  - platform: template
    name: $description Pump
    id: relay_pump_pub
    lambda: |-
      return id(relay_pump).state;
    turn_on_action:
      - logger.log: "Pump turn on"
      - if:
          condition:
            - binary_sensor.is_off: sump_low
          then:
            - switch.turn_on: relay_pump
    turn_off_action:
      - logger.log: "Pump turn off"
      - switch.turn_off: relay_pump

  - platform: template
    name: $description ATO Enabled
    id: ato_enabled
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: true
    turn_on_action:
      then:
        - script.execute: set_fill_valve_on_off
        - logger.log: "ATO Enable on"
    turn_off_action:
      then:
        - switch.turn_off: relay_valve
        - script.stop: fill_duration_guard
        - logger.log: "ATO Enable off"

  - platform: template
    name: $description Error Fill Duration Exceeded
    id: error_fill_duration_exceeded
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: true
