substitutions:
  name: controller051
  description: Aquarium 02
  static_ip: ""

# Enable logging
logger:

packages:
  base: !include include/base.yaml
  wifi: !include include/wifi_not.yaml


esphome:
  name: $name
  comment: $description
  platform: ESP32
  board: esp32doit-devkit-v1

globals:

  - id: error_fill_pump_duration_exceeded
    type: bool
    restore_value: yes
    initial_value: 'false'

  - id: enabled
    type: bool
    restore_value: yes
    initial_value: 'true'

script:

  - id: set_fill_pump_duration_exceeded
    then:
      - delay: 5min
      - globals.set:
          id: error_fill_pump_duration_exceeded
          value: 'true'
      - switch.turn_off: relay_valve

  - id: set_fill_valve
    then:
      - if:
          condition:
            and:
              - binary_sensor.is_off: reservoir_full_sensor
              #- binary_sensor.is_off: reservoir_full_backup_sensor
              - lambda: |-
                  return id(enabled) && !id(error_fill_pump_duration_exceeded);
          then:
            - switch.turn_on: relay_valve
            - script.execute: set_fill_pump_duration_exceeded
      - if:
          condition:
            or:
              - binary_sensor.is_on: reservoir_full_sensor
              #- binary_sensor.is_on: reservoir_full_backup_sensor
          then:
            - switch.turn_off: relay_valve
            - script.stop: set_fill_pump_duration_exceeded

binary_sensor:

  - platform: template
    name: $description Error Fill Duration Exceeded
    lambda: |-
      return id(error_fill_pump_duration_exceeded);

  - platform: template
    name: $description Enabled
    lambda: |-
      return id(enabled);

  - platform: gpio
    id: reservoir_full_sensor
    name: $description Full Sensor
    pin:
      number: GPIO27
      mode: INPUT_PULLUP
    filters:
      - delayed_on_off: 1000ms
    on_state:
      then:
        - script.execute: set_fill_valve

switch:

  - platform: gpio
    id: relay_valve
    pin: GPIO17
    restore_mode: ALWAYS_OFF

  # 674 ml per minute, 90s, 1012 ml, gikfun diaphram pump
  - platform: gpio
    id: relay_pump
    pin: GPIO16
    restore_mode: ALWAYS_OFF

  - platform: template
    name: $description Pump
    id: relay_pump_pub
    lambda: |-
      if (id(relay_pump).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - if:
          condition:
            - lambda: |-
                return id(enabled);
          then:
            - switch.turn_on: relay_pump
    turn_off_action:
      then:
        - switch.turn_off: relay_pump

  - platform: template
    name: $description Valve
    id: relay_valve_pub
    lambda: |-
      if (id(relay_valve).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - if:
          condition:
            - lambda: |-
                return id(enabled);
          then:
            - switch.turn_on: relay_valve
    turn_off_action:
      then:
        - switch.turn_off: relay_valve

light:
  - platform: monochromatic
    name: $description Light
    output: output_gpio_33
    restore_mode: ALWAYS_OFF

output:
  - platform: ledc
    id: output_gpio_33
    pin: GPIO33
    # 6
    #min_power: 0.001
    min_power: 0.002
    zero_means_zero: true

dallas:
  - pin: GPIO26

sensor:
  - platform: dallas
    address: 0x2D011921144A0228
    name: $description Temperature

api:
  services:

    - service: reset_error_fill_pump_duration_exceeded
      then:
        - logger.log:
            format: "Reseting pump duration error"
        - globals.set:
            id: error_fill_pump_duration_exceeded
            value: 'false'
