substitutions:
  name: controller051
  description: Aquarium 02
  static_ip: ""

# Enable logging
logger:

<<: !include include/common.yaml

esphome:
  name: $name
  comment: $description
  platform: ESP32
  board: esp32doit-devkit-v1

light:
  - platform: monochromatic
    name: $description Light
    output: output_gpio_33
    restore_mode: ALWAYS_OFF

output:
  - platform: ledc
    pin: GPIO33
    id: output_gpio_33
