substitutions:
  name: light054
  friendly_name: Kauf Bulb BR30

packages:
  kauf.rgbww: github://KaufHA/kauf-rgbww-bulbs/kauf-bulb.yaml

esphome:
  name_add_mac_suffix: false
  name: $name
  comment: $friendly_name

wifi:
  ssid: !secret iot_wifi
  password: !secret iot_wifi_password
