substitutions:
  name: switch044
  description: Wall Aquarium Display

# Enable logging
logger:

<<: !include include/common.yaml

esphome:
  name: $name
  comment: $description
  platform: ESP8266
  board: d1_mini

light:
  - platform: monochromatic
    name: $description Light 1
    output: output_component1
  - platform: monochromatic
    name: $description Light 2
    output: output_component2

output:
  - platform: esp8266_pwm
    id: output_component1
    pin: D6
  - platform: esp8266_pwm
    id: output_component2
    pin: D7
