esphome:
  name: switch001
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret iot_wifi
  password: !secret iot_wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Switch001 Fallback Hotspot"
    password: "M77ZKjHwUnjK"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

switch:
  - platform: gpio
    name: "Living Room Lamp"
    pin: GPIO14
    id: relay
