substitutions:
  name: switch028
  description: Aquarium Pump

# Enable logging
logger:

<<: !include include/common.yaml

esphome:
  name: $name
  comment: $description (Gosund WP5)
  platform: ESP8266
  board: esp01_1m

binary_sensor:
  - platform: gpio
    id: button_1
    pin: GPIO4
    filters:
      - invert:
      - delayed_off: 10ms
    name: $description Power Button
    on_press:
      then:
        - switch.toggle: relay_1

switch:
  - platform: gpio
    id: red_led
    pin: GPIO12
    inverted: true
  - platform: gpio
    id: blue_led
    pin: GPIO13
    inverted: true
    restore_mode: RESTORE_DEFAULT_ON
  - platform: gpio
    name: $description
    id: relay_1
    pin: GPIO14
    restore_mode: RESTORE_DEFAULT_ON
    on_turn_on:
      then:
        - script.stop: turn_on_timer
        - switch.turn_on: blue_led
        - switch.turn_off: red_led
    on_turn_off:
      then:
        - script.execute: turn_on_timer
        - switch.turn_off: blue_led
        - switch.turn_on: red_led

script:
  id: turn_on_timer
  then:
    - delay: 10min
    - switch.turn_on: relay_1
