substitutions:
  name: switch006
  description: Garage Fluorescent Light

ota:
  - platform: esphome

# Enable logging
logger:

<<: !include include/common.yaml
<<: !include include/sonoff_mini_light.yaml
