substitutions:
  name: switch004
  description: Aqurium Circulation Pump

ota:
  - platform: esphome

# Enable logging
logger:

<<: !include include/common.yaml

esphome:
  name: $name
  comment: $description
  platform: ESP8266
  board: esp01_1m

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO4
      inverted: true
    name: $description Power Button
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    id: red_led
    pin: GPIO12
    inverted: true
    name: $description Red LED
    restore_mode: RESTORE_DEFAULT_ON
  - platform: gpio
    id: blue_led
    pin: GPIO13
    inverted: true
    name: $description Blue LED
  - platform: gpio
    name: $description
    pin: GPIO14
    id: relay
    restore_mode: RESTORE_DEFAULT_ON
    on_turn_on:
      - switch.turn_on: blue_led
      - switch.turn_off: red_led
    on_turn_off:
      - switch.turn_on: red_led
      - switch.turn_off: blue_led
