substitutions:
  name: switch033
  description: Luke Bedroom Switch 2

ota:
  - platform: esphome

# Enable logging
logger:

<<: !include include/common.yaml
<<: !include include/gosund_wp5_light.yaml
