substitutions:
  name: switch003
  description: Garage Floor Fan

mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: false

# Enable logging
logger:

<<: !include include/common.yaml
<<: !include include/gosund_wp5_fan.yaml
