substitutions:
  name: switch031
  description: Living Room Floor Lamp

ota:
  - platform: esphome

# Enable logging
logger:

<<: !include include/common.yaml
<<: !include include/gosund_wp5_light.yaml
