substitutions:
  name: switch002
  description: !secret lamp_01_name

wifi:
  ssid: !secret iot_wifi
  password: !secret iot_wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Switch002 Fallback Hotspot"
    password: "BGQbSegkiQri"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

<<: !include include/gosund_wp5_light.yaml
