substitutions:
  name: switch003

esphome:
  name: switch003
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret iot_wifi
  password: !secret iot_wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Switch003 Fallback Hotspot"
    password: "N8P53r4rd8Cx"

mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: false

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

switch:
  - platform: gpio
    name: "switch003"
    pin: GPIO14
    id: relay

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO4
      inverted: true
    name: $name Power Button
    on_press:
      - switch.toggle: relay