notify:
  - name: aquarium_ato_wc_group
    platform: group
    services:
      - service: mobile_app_jeremy
      - service: pushover_jeremy

# Home Assistant configuration
input_number:
  servo_control_drain_pump:
    name: Drain Pump Control
    initial: 0
    min: 0
    max: 100
    step: 1
    mode: slider
  servo_control_fill_pump:
    name: Fill Pump Control
    initial: 0
    min: 0
    max: 100
    step: 1
    mode: slider

automation:
  - alias: Auto Water Change
    trigger:
      platform: time
      at:
        - "01:00:00"
        - "02:00:00"
    action:
      repeat:
        while:
          - condition: template
            value_template: "{{ repeat.index <= 10 }}"
        sequence:
          - service: esphome.controller038_run_drain_pump
          - delay: "00:01:30"

  - alias: Auto Water Change Daphnia Tank
    # 10 percent = 730ml per minute, 25L tank, 3.5 minutes.
    #  5 percent = 730ml per minute, 25L tank, 1.75 minutes.
    trigger:
      platform: time
      at:
        - "04:00:00"
    condition:
      condition: state
      entity_id: binary_sensor.drain_sump_reservoir_full_sensor
      state: "off"
    action:
      - service: switch.turn_on
        target:
          entity_id: switch.daphnia_ato_wc_pump
      - delay: "00:03:30"
      - service: switch.turn_off
        target:
          entity_id: switch.daphnia_ato_wc_pump

#  - alias: Auto Water Change Counter Aquarium
#    # 74 liter total volume
#    #  15 percent = 13.3 minutes
#    #  10 percent = 8.8 minutes
#    #   5 percent = 4.4 minutes
#    #       2 min = 2.3 %
#    #       4 min = 4.5 %
#    trigger:
#      platform: time
#      at:
#        - "10:30:00"
#        #- "10:45:00"
#    condition:
#      - condition: state
#        entity_id: binary_sensor.drain_sump_reservoir_full_sensor
#        state: "off"
#      #- condition: time
#      #  weekday:
#      #    - mon
#      #    - fri
#    action:
#      - service: switch.turn_on
#        target:
#          entity_id: switch.aquarium_02_pump
#      - delay: "00:02:00"
#      - service: switch.turn_off
#        target:
#          entity_id: switch.aquarium_02_pump
#
#  - alias: Write Drain Pump Value to ESP
#    trigger:
#      platform: state
#      entity_id: input_number.servo_control_drain_pump
#    action:
#      # Replace livingroom with the name you gave the ESP
#      - service: esphome.controller038_control_drain_pump
#        data_template:
#          level: "{{ trigger.to_state.state | int }}"

  - alias: Write Fill Pump 2 Value to ESP
    trigger:
      platform: state
      entity_id: input_number.servo_control_fill_pump
    action:
      # Replace livingroom with the name you gave the ESP
      - service: esphome.controller038_control_fill_pump
        data_template:
          level: "{{ trigger.to_state.state | int }}"

  - alias: Daphnia Tank Full Backup Sensor Alarm
    trigger:
      - entity_id: binary_sensor.daphnia_ato_wc_reservoir_full_backup_sensor
        platform: state
        from: "off"
        to: "on"
        for: "00:00:10"
    action:
      - service: notify.aquarium_ato_wc_group
        data:
          message: Daphnia Tank Full Backup Sensor is on!

  - alias: Drain Sump Full Alarm
    trigger:
      - entity_id: binary_sensor.drain_sump_reservoir_full_sensor
        platform: state
        from: "off"
        to: "on"
        for: "00:05:00"
    action:
      - service: notify.aquarium_ato_wc_group
        data:
          message: Drain Sump full for too long!
