# Home Assistant configuration
input_number:
  servo_control_drain_pump:
    name: Drain Pump Control
    initial: 0
    min: 0
    max: 100
    step: 1
    mode: slider
  servo_control_fill_pump:
    name: Fill Pump Control
    initial: 0
    min: 0
    max: 100
    step: 1
    mode: slider


automation:
  - alias: Write Drain Pump Value to ESP
    trigger:
      platform: state
      entity_id: input_number.servo_control_drain_pump
    action:
      # Replace livingroom with the name you gave the ESP
      - service: esphome.controller038_control_drain_pump
        data_template:
          level: "{{ trigger.to_state.state | int }}"
  - alias: Write Fill Pump 2 Value to ESP
    trigger:
      platform: state
      entity_id: input_number.servo_control_fill_pump
    action:
      # Replace livingroom with the name you gave the ESP
      - service: esphome.controller038_control_fill_pump
        data_template:
          level: "{{ trigger.to_state.state | int }}"
