# Home Assistant configuration
input_number:
  servo_control_1:
    name: Pump 1 Control
    initial: 0
    min: 0
    max: 100
    step: 1
    mode: slider
  servo_control_2:
    name: Pump 2 Control
    initial: 0
    min: 0
    max: 100
    step: 1
    mode: slider


automation:
  - alias: Write Pump 1 Value to ESP
    trigger:
      platform: state
      entity_id: input_number.servo_control_1
    action:
      # Replace livingroom with the name you gave the ESP
      - service: esphome.controller038_control_pump_1
        data_template:
          level: "{{ trigger.to_state.state | int }}"
  - alias: Write Pump 2 Value to ESP
    trigger:
      platform: state
      entity_id: input_number.servo_control_2
    action:
      # Replace livingroom with the name you gave the ESP
      - service: esphome.controller038_control_pump_2
        data_template:
          level: "{{ trigger.to_state.state | int }}"
