automation:

  - alias: Bedroom lamp button long press
    description: ""
    trigger:
      - platform: state
        entity_id:
          - sensor.button_0057_action
        to: long
    action:
      - service: light.turn_on
        target:
          entity_id: light.bulb_0056
        data:
          rgb_color:
            - 255
            - 0
            - 0
          brightness_pct: 15
    mode: single

  - alias: Bedroom lamp button single turn off
    description: ""
    trigger:
      - platform: state
        entity_id:
          - sensor.button_0057_action
        to: single
    condition:
    - condition: state
      entity_id: light.bulb_0056
      state: "on"
    action:
      - service: light.turn_off
        target:
          entity_id: light.bulb_0056
    mode: single

  - alias: Bedroom lamp button single turn on
    description: ""
    trigger:
      - platform: state
        entity_id:
          - sensor.button_0057_action
        to: single
    condition:
    - condition: state
      entity_id: light.bulb_0056
      state: "off"
    action:
      - service: light.turn_on
        data:
          color_temp: 270
          brightness_pct: 0
          transition: 0
        target:
          entity_id: light.bulb_0056
      - service: light.turn_on
        data:
          transition: 0
          brightness_pct: 100
          color_temp: 270
        target:
          entity_id: light.bulb_0056
    mode: single
