automation:
  - alias: Doorbell notification
    description: ''
    trigger:
    - entity_id: binary_sensor.doorbell
      from: 'off'
      platform: state
      to: 'on'
    condition: []
    mode: single
    action:
    - data:
        message: Someone rang the doorbell!
        title: Doorbell
      service: notify.mobile_app_adults
    - data:
        entity_id: media_player.basement_speaker
        media_content_id: !secret url_doorbell_mp3
        media_content_type: 'music'
      service: media_player.play_media
    - data:
        entity_id: media_player.living_room_speaker
        media_content_id: !secret url_doorbell_mp3
        media_content_type: 'music'
      service: media_player.play_media
    - data:
        entity_id: media_player.dining_room_speaker
        media_content_id: !secret url_doorbell_mp3
        media_content_type: 'music'
      service: media_player.play_media
    - data:
        entity_id: media_player.garage_speaker
        media_content_id: !secret url_doorbell_mp3
        media_content_type: 'music'
      service: media_player.play_media
