# https://community.home-assistant.io/t/i-did-it-i-defeated-the-horrible-google-home-cast-start-prompt-sound/36123/40
# https://github.com/anars/blank-audio

automation:
  - alias: keepalive_basement_speaker
    trigger:
      platform: time_pattern
      minutes: "/2"
      seconds: "30"
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: media_player.basement_speaker
          state: "off"
        - condition: state
          entity_id: media_player.basement_speaker
          state: "idle"
    action:
      - service: media_player.play_media
        entity_id: media_player.basement_speaker
        data:
          media_content_id: !secret url_silent_mp3
          media_content_type: music

  - alias: keepalive_dining_room_speaker
    trigger:
      platform: time_pattern
      minutes: "/2"
      seconds: "30"
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: media_player.dining_room_speaker
          state: "off"
        - condition: state
          entity_id: media_player.dining_room_speaker
          state: "idle"
    action:
      - service: media_player.play_media
        entity_id: media_player.dining_room_speaker
        data:
          media_content_id: !secret url_silent_mp3
          media_content_type: music

  - alias: keepalive_garage_speaker
    trigger:
      platform: time_pattern
      minutes: "/2"
      seconds: "30"
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: media_player.garage_speaker
          state: "off"
        - condition: state
          entity_id: media_player.garage_speaker
          state: "idle"
    action:
      - service: media_player.play_media
        entity_id: media_player.garage_speaker
        data:
          media_content_id: !secret url_silent_mp3
          media_content_type: music
