# https://github.com/home-assistant/hassio-addons/issues/1445#issuecomment-668547727

sensor:
  - platform: template
    sensors:
      cert_expiry_ha:
        value_template: "{{ ((as_timestamp(states('sensor.cert_expiry_timestamp_ha')) - now().timestamp()) / 86400) | round(1) }}"
      cert_expiry_nas:
        value_template: "{{ ((as_timestamp(states('sensor.cert_expiry_timestamp_nas')) - now().timestamp()) / 86400) | round(1) }}"
      cert_expiry_prox:
        value_template: "{{ ((as_timestamp(states('sensor.cert_expiry_timestamp_prox')) - now().timestamp()) / 86400) | round(1) }}"

automation:
  # Renew certificates and restart homeassistant when cert expires in less than 30 days
  - alias: system_letsencrypt_renewal
    trigger:
      - platform: time
        at: 03:00:00
    condition:
      - condition: numeric_state
        entity_id: sensor.cert_expiry_ha
        below: 30
    action:
      - service: hassio.addon_restart
        data:
          addon: core_letsencrypt
      - delay: 00:05:00
      - service: homeassistant.restart
