automation:

- alias: "Delivery Notification USPS"
  initial_state: 'on'
  trigger:
    platform: numeric_state
    entity_id: sensor.mail_usps_delivered
    above: 0
  action:
    - service: notify.mobile_app_jeremy_phone
      data_template:
        title: "USPS Delivery!"
        message: "Total USPS packages today is: {{ states('sensor.mail_usps_delivered') }}"

- alias: "Delivery Notification UPS"
  initial_state: 'on'
  trigger:
    platform: numeric_state
    entity_id: sensor.mail_ups_delivered
    above: 0
  action:
    - service: notify.mobile_app_jeremy_phone
      data_template:
        title: "UPS Delivery!"
        message: "Total UPS packages today is: {{ states('sensor.mail_ups_delivered') }}"

- alias: "Delivery Notification Fedex"
  initial_state: 'on'
  trigger:
    platform: numeric_state
    entity_id: sensor.mail_fedex_delivered
    above: 0
  action:
    - service: notify.mobile_app_jeremy_phone
      data_template:
        title: "Fedex Delivery!"
        message: "Total Fedex packages today is: {{ states('sensor.mail_fedex_delivered') }}"
