automation:
  - alias: 'School Bell MS'
    condition:
      condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    trigger:
      platform: time
      at:
        # HR
        - "08:00:00"
        # 1st
        - "08:30:00"
        - "09:43:00"
        # 2nd
        - "09:48:00"
        - "10:45:00"
        # 3rd
        - "10:48:00"
        - "11:48:00"
        #- "12:13:00"
        # Lunch ??
        #- "11:48:00"
        #- "12:18:00"
        # 4th
        - "12:18:00"
        - "13:18:00"
        # 5th
        - "13:23:00"
        - "14:23:00"
        # 6th
        - "14:28:00"
        - "15:30:00"
    action:
      - service: media_player.play_media
        entity_id: media_player.basement_speaker
        data:
          media_content_id: !secret url_bt_loop5_mp3
          media_content_type: music

  - alias: 'School Bell HS'
    condition:
      condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    trigger:
      platform: time
      at:
        # HR
        - "08:00:00"
        # 1st
        - "08:30:00"
        - "09:50:00"
        # Advisory
        - "09:56:00"
        - "10:41:00"
        # 2nd
        - "10:47:00"
        - "12:07:00"
        # 3rd
        - "12:13:00"
        - "14:02:00"
        # Lunch ??
        # 4th
        - "14:18:00"
        - "15:30:00"
    action:
      - service: media_player.play_media
        entity_id: media_player.dining_room_speaker
        data:
          media_content_id: !secret url_bt_loop5_mp3
          media_content_type: music
