notify:
  - name: water_sensor_group_emergency
    platform: group
    services:
      - service: pushover_jeremy
        data:
          data:
            sound: echo
            priority: 2
            retry: 30
            expire: 3600
      - service: mobile_app_adults
  - name: water_sensor_group
    platform: group
    services:
      - service: mobile_group_adults

automation:

- alias: Aquarium Water Sensor Alarm
  trigger:
  - entity_id: binary_sensor.water_sensor_0050
    platform: state
    from: 'off'
    to: 'on'
  action:
    - service: notify.water_sensor_group_emergency
      data:
        message: Aquarium water sensor alarm triggered!

- alias: Drain Tank Water Sensor Alarm
  trigger:
  - entity_id: binary_sensor.water_sensor_0036
    platform: state
    from: 'off'
    to: 'on'
  action:
    - service: notify.water_sensor_group_emergency
      data:
        message: Drain Tank water sensor alarm triggered!

- alias: Washing Machine Water Sensor Alarm
  trigger:
  - entity_id: binary_sensor.water_sensor_0035
    platform: state
    from: 'off'
    to: 'on'
  action:
    - service: notify.water_sensor_group_emergency
      data:
        message: Washing Machine water sensor alarm triggered!

- alias: Washing Machine Battery Sensor Alarm
  trigger:
  - entity_id: sensor.water_sensor_0035_battery_level
    platform: numeric_state
    below: 25
  action:
    - service: notify.water_sensor_group
      data:
        message: Washing Machine battery sensor alarm triggered.
